version: "3.9"

services:
  postgres:
    image: postgres:16

    container_name: geo-postgres

    restart: always

    environment:
      POSTGRES_USER: geo_user
      POSTGRES_PASSWORD: geo_password
      POSTGRES_DB: geo_engine

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
